import Navbar from '@/components/Navbar/Navbar'
import './globals.css'
// import { Inter } from 'next/font/google'
import Footer from '@/components/Footer/Footer'

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'next irfan hero',
  description: 'Generated by create next project',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='px-8'>
      
       <Navbar></Navbar>
        {children}
        <Footer />
       
        </body>
    </html>
  )
}
